name: Build

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Compile all Java sources
        run: |
          mkdir -p out
          javac -d out $(find . -name "*.java")

      - name: Create JAR with correct Main-Class
        run: |
          mkdir -p jar
          echo "Main-Class: vazkii.instancesync.InstanceSync" > manifest.txt
          jar cfm jar/InstanceSync.jar manifest.txt -C out .

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: instance-sync-jar
          path: jar/InstanceSync.jar
